services:
  db:
    image: mysql:8.0
    container_name: mysql_sidat
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: sidat
    ports:
      - "3307:3306"
    volumes:
      - sidat_data:/var/lib/mysql
    networks:
      - taller-network # Agregamos la red
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p12345"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: taller_web_app
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - taller-network # Agregamos la misma red
    environment:
      DB_HOST: db # Esto le dice a Spring que busque 'db'
      DB_USER: root
      DB_PASS: 12345

networks:
  taller-network: # Definimos la red al final
    driver: bridge

volumes:
  sidat_data: